name: first workflow

on: workflow_dispatch

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello jaskaran"
        run: echo "this is running now..."
      - name: Print goodbye
        run: echo 'Done -bye dear'
        
    
